# Generated by Django 3.2.4 on 2022-04-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0031_auto_20210621_1206"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePeriodicTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(max_length=64, verbose_name="修改人")),
                ("end_at", models.DateTimeField(null=True, verbose_name="结束时间")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否软删除"),
                ),
                ("is_builtin", models.BooleanField(default=False, verbose_name="是否内置")),
                (
                    "project_key",
                    models.CharField(default=0, max_length=32, verbose_name="项目key"),
                ),
                ("service_id", models.IntegerField(verbose_name="服务ID")),
                ("crontab_config", models.JSONField(default=[], verbose_name="调度策略")),
                (
                    "celery_task_ids",
                    models.JSONField(default=[], verbose_name="关联的定时任务列表"),
                ),
                ("config", models.JSONField(default={}, verbose_name="其他额外配置信息,提单字段")),
                (
                    "timezone",
                    models.CharField(default="UTC", max_length=32, verbose_name="时区"),
                ),
                (
                    "total_run_count",
                    models.IntegerField(default=0, verbose_name="执行次数"),
                ),
            ],
            options={
                "verbose_name": "服务周期任务配置表",
                "verbose_name_plural": "服务周期任务配置表",
            },
        ),
    ]
